### ISSUE TITLE
ubuntu build error

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.py#1]
I'm aware that it's failing on the C++ side, but I'm reporting it here so you can decide where this information should be.

I cloned the repo, ran make and got this:
```
erik@erik-linux:~/csBigInteger.py$ make
g++ --shared csBigIntegerpp/src/csBigIntegerLib.cpp csBigIntegerpp/src/BigInteger.cpp -lgmp -lgmpxx -o csbiginteger/csbiginteger.so -fPIC
csBigIntegerpp/src/BigInteger.cpp:10:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

It is nowhere mentioned that you need to install `libgmp3-dev`
```
sudo apt-get install libgmp3-dev
```
Would be good to mention the required build tools somewhere to avoid people having to google for them

**Comment by igormcoelho** [comment]
In fact I didnt know that, thanks! I already had this lib haha but I'll update instructions.

**Comment by igormcoelho** [comment]
Created a `make vendor` command here, that compiles `csbiginteger.so` library... in fact, there's  no `make` here now, because this library is just a dependency, and python project itself does not require any make ;)
