### ISSUE TITLE
`to_int()` unexpected conversion

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.py#4]
Not sure what's going on here but my current expectation is that `to_int()` returns a signed integer. In this example the value is to big to fit in a 32-bit signed integer and should raise an exception
```python
In [23]: b1 = BigInteger(3573895253)                                           

In [24]: b1.to_int()                                                           
Out[24]: -721072043
```

in C#
```
            BigInteger b1 = new BigInteger(3573895253);
            int b = (int) b1; <- Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
```

**Comment by igormcoelho** [comment]
Max int is two billions (32 bits). To_long will allow you pass this limit a little bit (up to 64bits). After that, will need to integrate with some parsinglib on python, from string input. But I got your point.. ints are giant on python.

**Comment by igormcoelho** [comment]
In fact,best thong would be launching an exception, just like C#. Better crash the same way, right?

**Comment by ixje** [comment]
if `to_int()` is supposed to mimic C#'s cast to `int` then yes we should throw an error to get the same behaviour. You can use https://docs.python.org/3/library/exceptions.html#OverflowError

**Comment by igormcoelho** [comment]
overflowing now:
```py
>>> from csbiginteger.BigInteger import BigInteger
>>> b1 = BigInteger(3573895253)      
>>> b1
3573895253
>>> b1.to_int()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/imcoelho/git-reps/csBigInteger.py/csbiginteger/BigInteger.py", line 112, in to_int
    raise OverflowError("overflow on signed int32")
OverflowError: overflow on signed int32
```
