### ISSUE TITLE
unnatural Python interface

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.py#5]
I think we can improve the usage of this library. Currently it feels very unnatural to use. 
1) addition and subtraction requires to call `.add()` or `sub()` e.g. `b3 = b1.add(b2)`, instead we should be able to just use `b3 = b1 + b2`. I suggest to implement `__add__` , `__sub__` etc methods
2) cannot directly inspect the value
```python
In [1]: from csbiginteger.BigInteger import BigInteger                         

In [2]: b1 = BigInteger(123)                                                   

In [3]: b1                                                                     
Out[3]: <csbiginteger.BigInteger.BigInteger at 0x7f33e72b4400>
```
compare this to for example neo-python's implementation
```python
In [1]: from neo.Core.BigInteger import BigInteger                             

In [2]: b1 = BigInteger(123)                                                   

In [3]: b1                                                                     
Out[3]: 123
```
You'll want to implement `__repr__` and probably also `__str__`
That should also fix that printing does not give the value
```python
In [5]: print(b1)                                                              
<csbiginteger.BigInteger.BigInteger object at 0x7f33e72b4400>
```
expected would be 
```python
In [6]: print(b1)                                                              
123
```

**Comment by igormcoelho** [comment]
Oh thanks, I didnt know these things on python. I'll see these.

**Comment by igormcoelho** [comment]
Regarding `print()`, default should be base16 or base10? On C#, "default" is `0xabcd` standard, but that's not what you are expecting here. Should `print()` and `to_string` return different things?

**Comment by ixje** [comment]
to me `print(big_integer_object)` should print the value of the BigInteger
`to_string()` can probably be dropped as Python users never call such a thing. They would do `str(big_integer_object)` if they really needed to enforce a string. It could just become some internal helper function

**Comment by igormcoelho** [comment]
This works now:
```py
>>> y = BigInteger(255)
>>> y
255
>>> int(str(y))+1
256
```

**Comment by ixje** [comment]
great!

**Comment by igormcoelho** [comment]
This works now too:
```py
>>> y = BigInteger(1)
>>> y+1
2
```

**Comment by igormcoelho** [comment]
Created `floordiv` operator: `y//2`. Do you think we need to create `realdiv`? It won't do any float arithmetics, perhaps it's better to let it crash on `y/2`. 
What do you think?

**Comment by ixje** [comment]
Real div is needed. There are many cases in the code where a BigInteger / BigInteger is used. That it uses floordiv under the hood is an implementation detail. This is what neo-python currently does because `BigInt(-1) / BigInt(2)` behaves differently in the regular python language from C#.
```python
    def __floordiv__(self, *args, **kwargs):
        return BigInteger(super(BigInteger, self).__floordiv__(*args, **kwargs))

    def __truediv__(self, *args, **kwargs):  # real signature unknown
        if self < 0:
            return BigInteger(super(BigInteger, self).__truediv__(*args, **kwargs))
        else:
            return BigInteger(super(BigInteger, self).__floordiv__(*args, **kwargs))
```

**Comment by ixje** [comment]
while you're at it, please don't forget to add `__eq__` because this fails and shouldn't
```python
In [1]: from csbiginteger.BigInteger import BigInteger                                                                                  

In [2]: b1 = BigInteger(1)                                                                                                              

In [3]: b2 = BigInteger(1)                                                                                                              

In [4]: b1 == b2                                                                                                                        
Out[4]: False
```

**Comment by igormcoelho** [comment]
Ok, comparisons are working now:
```py
>>> from csbiginteger.BigInteger import BigInteger
>>> y = BigInteger(-1)
>>> x = BigInteger(b'\xff')
>>> y == x
True
>>> z = BigInteger(0)
>>> y == z
False
```

**Comment by igormcoelho** [comment]
Whats the expected result of:
```py
>>> BigInteger(-1)/BigInteger(2)
0
```
correct? it's truediv happening as it was a floordiv...

**Comment by ixje** [comment]
you can try running this
```python
from unittest import TestCase
class BigIntegerTestCase(TestCase):
    def test_big_integer_div2(self):
        b1 = BigInteger(41483775933600000000)
        b2 = BigInteger(414937759336)

        b3 = b1 / b2
        b4 = b1 // b2
        self.assertIsInstance(b3, BigInteger)
        self.assertEqual(b3, 99975899)
        self.assertEqual(b4, b3)

    def test_big_integer_div_rounding(self):
        b1 = BigInteger(1)
        b2 = BigInteger(2)
        self.assertEqual(0, b1 / b2)  # 0.5 -> 0

        b1 = BigInteger(2)
        b2 = BigInteger(3)
        self.assertEqual(0, b1 / b2)  # 0.66 -> 0

        b1 = BigInteger(5)
        b2 = BigInteger(4)
        self.assertEqual(1, b1 / b2)  # 1.25 -> 1

        b1 = BigInteger(5)
        b2 = BigInteger(3)
        self.assertEqual(1, b1 / b2)  # 1.66 -> 1

        b1 = BigInteger(-1)
        b2 = BigInteger(3)
        self.assertEqual(0, b1 / b2)  # -0.33 -> 0

        b1 = BigInteger(-5)
        b2 = BigInteger(3)
        self.assertEqual(-1, b1 / b2)  # -1.66 -> -1

    def test_big_integer_div_block1473972(self):
        b1 = BigInteger(-11001000000)
        b2 = BigInteger(86400)
        result = b1 / b2
        self.assertEqual(-127326, result)
```

**Comment by igormcoelho** [comment]
Could you create a test class for us here on this project? I don't have any experience on this... we can give you direct write access to repo if you prefer (just did it).

**Comment by igormcoelho** [comment]
All tests passed. Basic structure should be fully working by now ;)

**Comment by ixje** [comment]
sorry should have added the instruction how to run the test. My IDE picks it up automatically, but I should not have assumed you use an IDE for python.
