### ISSUE TITLE
to_bytearray() incorrect

### ISSUE THREAD

**Issue by ixje** [NeoResearch/csBigInteger.py#6]
This following is a specific case encountered on NEO TestNet and currently fails for this lib.
```python
        b6 = BigInteger(-48335248028225339427907476932896373492484053930)
        b6ba = b6.to_bytearray()
        self.assertEqual(20, len(b6ba))
```
It instead it returns 8 bytes

**Comment by igormcoelho** [comment]
I think initialization is the problem: `if type(param) is int:` was intended only for `int32`, not global python ints (which are other types of bigints).
I have an idea, will internally pass as str for all cases, solving all issues.

**Comment by igormcoelho** [comment]
Passing now:
```py
>>> b6 = BigInteger(-48335248028225339427907476932896373492484053930)
>>> b6ba = b6.to_bytearray()
>>> len(b6ba)
20
```
