### ISSUE TITLE
use total ordering libs to define only __eq__ and __lt__

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/csBigInteger.py#8]
@ixje I think we should define only == and > operators, and let python define the rest. It's simpler and safer, but I don't know how to use these decorators in a nice "pythonic" way. Could you help?

**Comment by ixje** [comment]
I can probably help but I first need to better understand the issue you're trying to solve.
> I think we should define only == and > operators, and let python define the rest
1) Define `==` and `> ` operators where? In the C++ module? 
2) "define the rest" , which rest? 

all "natural" operators like `+`, `-`, `/` , `%` etc work if they have their equivalent `__<something>__` dunder methods implemented. Given that this BigInteger class does not derive from e.g. Python's buildin `int` or `float` it will not know what todo with the mentioned operators unless we implement `__add__`, `__sub__`  etc.

**Comment by igormcoelho** [comment]
Man, turns out I just found this amazing lib on python: https://docs.python.org/2/library/functools.html#functools.total_ordering
Very easy to use, two lines hahaha all comparisons are working already now ;)
